name: bpnet
channels:
- bioconda
- pytorch
- conda-forge
- anaconda
dependencies:
- python=3.6
- git

- pybedtools=0.7.10
- bedtools=2.27.1
- pybigwig=0.3.18
- pysam=0.15.3
- genomelake=0.1.4

- tensorflow-gpu=1.15
- kipoi=0.6.25
- kipoiseq=0.3.4
- pytorch=1.9.0  # optional for data-loading
- cudatoolkit=10.0
- requests=2.28.1
- cython=0.29.24
- joblib=0.15.1
- h5py=2.9.0
- numpy=1.17.5
- tqdm=4.46.1
- scipy=1.4.1
- statsmodels=0.11.1
- scikit-learn=0.21.3

- pandas=1.0.3
- fastparquet=0.4.0
- python-snappy=0.6.0

- nb_conda=2.2.1
- pip=21.3.1
- pip:
  - git+https://github.com/kundajelab/DeepExplain.git
  # bpnet package
  - .[dev,extras]  # install the local basepair package. All the other required pip packages are specified in the setup.py
